### ISSUE TITLE
Master List: Port over pages and components and other files

### ISSUE THREAD

**Issue by bretthayes** [sourcegraph/about-replatform#48]
# Pages
- [x] 404.tsx #14
- [x] about.tsx #66
- [x] accelerate-dev-onboarding.tsx #43
- [x] batch-changes.tsx #64 
- [x] blog.tsx #58 
- [x] case-studies/ #2 #3 
  - [x] cern-reduces-technical-debt.tsx
  - [x] cloudflare-accelerates-debugging-and-improves-security.tsx
  - [x] convoy-improved-on-boarding.tsx
  - [x] convoy-software-engineers-and-data-scientists-work-better-together.tsx
  - [x] criteo-tackles-big-code.tsx
  - [x] f5-streamlines-collaboration-globally.tsx
  - [x] factset-migrates-from-perforce-to-github.tsx
  - [x] indeed-accelerates-development-velocity.tsx
  - [x] index.tsx
  - [x] lyft-monolith-to-microservices.tsx
  - [x] nutanix-fixed-log4j-with-sourcegraph.tsx #68 
  - [x] quantcast-large-scale-refactoring.tsx
  - [x] sofi-moves-fast-on-hundreds-of-microservices.tsx
  - [x] we-are-thorn.tsx
  - [x] workiva-automates-large-scale-code-changes.tsx
- [x] cloud-beta.tsx #85
- [x] code-insights.tsx #86
- [x] code-search.tsx #74 
- [x] community.tsx #71 
- [x] demo.tsx #61 
- [x] contact/ #24 #25 
  - [x] index.tsx
  - [x] product-specialist.tsx
  - [x] request-batch-changes-demo.tsx
  - [x] request-code-change-management-demo.tsx
  - [x] request-code-insights-demo.tsx
  - [x] request-demo.tsx
  - [x] request-info.tsx
  - [x] request-trial.tsx
- [x] dev-tools-quiz.tsx #87
- [x] ~~dotgo.tsx~~ deprecated page #88
- [x] fixing-vulnerabilities.tsx #43
- [x] get-started/ #28 
  - [x] cloud.tsx
  - [x] getStarted.module.scss
  - [x] index.tsx
  - [x] self-hosted.tsx
- [x] ~~github-universe.tsx~~ not porting, deprecated page #89
- [x] ~~go.tsx~~ not porting, deprecated page #90
- [x] ~~graphql.tsx~~ not porting, deprecated page #91
- [x] guides/ #116 
  - [x] continuous-developer-onboarding/
    - [x] index.module.scss
    - [x] index.tsx
  - [x] dev-onboarding-how-is-it-unique #149
    - [x] index.module.scss
    - [x] index.tsx
- [x] hackathons.tsx #92
- [x] index.tsx #40 
- [x] jobs.tsx #93
- [x] news.tsx #46 
- [x] podcast.tsx #42 
- [x] press-release.tsx #94
- [x] pricing.tsx #62 
- [x] privacy/ #43 
  - [x] cookie-policy.tsx
- [x] resources/ #44 
  - [x] abcs-book.tsx
  - [x] universal-code-search-ebook.tsx
- [x] ~~sl.tsx~~ not porting, deprecated page #95
- [x] ~~strange-loop.tsx~~ not porting, deprecated page #96
- [x] support.tsx #76 
- [x] uninstall.tsx #97
- [x] use-cases/
  - [x] index.tsx #14
  - [x] useCases.module.scss #14
  - [x] incident-response.tsx #131
  - [x] onboarding.tsx #41
  - [x] vulnerabilities.tsx #41
  - [x] code-reuse.tsx #143 
  - [x] code-health.tsx #132 
- [x] white-papers/ #44 
  - [x] abcs-book.tsx
  - [x] universal-code-search-ebook.tsx

# Components
- [x] BackButton.tsx #36 
- [x] Blockquote.tsx #64
- [x] BlogListItem.tsx #41 
- [x] BoardSection.tsx #66
- [x] ~~BrowserInstallButtons.tsx~~ unused/not porting
- [x] CustomCarousel.tsx #73 
- [x] ~~EventsList.tsx~~ unused/not porting
- [x] ~~EventsSection.tsx~~ unused/not porting
- [x] Footer.tsx #26
- [x] FormLegal.tsx #43
- [x] Header.tsx #26 
- [x] ~~HoverablePopover.tsx~~ unused/not porting
- [x] HubSpot.tsx #37 #51
- [x] ~~IconItem.tsx~~ unused/not porting
- [x] Install/ #28 
  - [x] index.tsx
  - [x] install.module.scss
- [x] IntegrationsSection.tsx #74 
- [x] Jumbotron.tsx #3 
- [x] Layout.tsx #26 
- [x] LeadershipSection.tsx #66
- [x] NewsList.tsx #46 
- [x] ~~PageSectionLinks.tsx~~ unused/not porting
- [x] QuoteCarousel/ #73 
  - [x] QuoteCarousel.module.scss
  - [x] index.tsx
- [x] SelfHostedSection.tsx #74
- [x] ~~ServerVersionNumber.tsx~~ unused/not porting
- [x] ~~Sprinkles.tsx~~ unused/not porting
- [x] ~~SprinklesHome.tsx~~ unused/not porting
- [x] ~~Subscribe.tsx~~ unused/not porting
- [x] TabCarousel.tsx #39 
- [x] TemplateCodeBlock.tsx #86 
- [x] ~~TestimonialCarousel.tsx~~ unused/not porting
- [x] TrySourcegraph.tsx #3
- [x] ~~Tweets.tsx~~ unused/not porting
- [x] YouTube.tsx #44 
- [x] blog/ #33 
  - [x] BlogHeadLinks.tsx
  - [x] BlogHeader.tsx
  - [x] BlogPost.tsx
  - [x] LinkPost.tsx
  - [x] PodcastPost.tsx
  - [x] PostsList.tsx
  - [x] PostsListPage.tsx
  - [x] PressReleasePost.tsx
  - [x] ReleasePost.tsx
  - [x] postTypes.tsx
- [x] code-insights/ #86 
  - [x] CodeInsightsExamples.module.scss
  - [x] CodeInsightsExamples.tsx
  - [x] components
  - [x] constants.ts
  - [x] mock-data.tsx
  - [x] types.ts
- [x] content/
  - [x] CaseStudyPage.tsx #3
  - [x] ContentPage.tsx #25 
  - [x] ContentSection.tsx #3
  - [x] WhitePaperPage.tsx #45 
- [x] podcast/ #42 
  - [x] PodcastSubscribeLinks.tsx
- [x] pricing/ #62 
  - [x] ~~PricingFreeTierPopover.tsx~~ unused/not porting
  - [x] PricingPlan.tsx
  - [x] PricingPlanFeature.tsx
  - [x] PricingPlanProperty.tsx
- [x] product/
  - [x] CaseStudiesSection.tsx #3
  - [x] CustomerLogosSection.tsx #119 
  - [x] CustomerLogosSectionAnimated.tsx #29
  - [x] ~~EbookUniversalCodeSearch.tsx~~ unused/not porting
  - [x] ~~EnterpriseReadySolution.tsx~~ unused/not porting
  - [x] ~~GitLabIntegrationSection.tsx~~ unused/not porting
  - [x] ~~OpenSourcePrivacyFeatureItem.tsx~~ unused/not porting
  - [x] ~~ProductDemoVideo.tsx~~ unused/not porting
  - [x] ~~SupportedProgrammingLanguagesLink.tsx~~ unused/not porting
  - [x] ~~UseCasesTable.tsx~~ unused/not porting

# Other
- [x] css/ #4 
- [x] data/
  - [x] news-listing.json #46 
  - [x] ~~events-listing.json~~ unused/not porting
- [x] hooks/
  - [x] carousel.ts #73 
  - [x] hubSpot.ts #25
- [x] images/about #66
- [x] templates/
  - [x] ContentTemplate.tsx #19
  - [x] PodcastEpisodeTemplate.tsx #42 
  - [x] PostTemplate.tsx #32
- [x] utils/ 
  - [x] event-logger.ts #102
- [x] html.tsx #1 
- [x] tracking.ts #64
- [x] static/ #4 
- [x] netlify.toml #10
